#ifndef CONSTANTS_H
#define CONSTANTS_H

// CLIENT CONSTANTS
#define ARGC 3
#define HOST 1
#define PORT 2

// SERVER CONSTANTS
#define ARGC_SERVER 2
#define SERVER_PORT 1
#define SERVER_CLOSE 'q'
#define CLIENT_QUEUE_LEN 100
#define MIN_PLAYERS_TO_START 1 //CAMBIAR A 2 AL ENTREGAR TP!
#define MAX_PLAYERS_PER_GAME 8
#define MAX_SPEED 10000
#define MAX_LIFE 1000
#define MAX_NITRO 500
#define MAX_TIME_PER_RACE 600000 // en ms creo
#define MAX_TIME_PER_WORKSHOP 10000 
#define NITRO_CONSUMPTION 5
#define NITRO_RECHARGE_RATE 2
#define NITRO_MULTIPLIER 2
#define MIN_NAME_LEN 3
#define MAX_NAME_LEN 16
#define ACCELERATION_PRICE 30
#define HANDLING_PRICE 10
#define NITRO_PRICE 40
#define LIFE_PRICE 25
#define MASS_PRICE 25
#define BRAKE_PRICE 25
#define ACCELERATION_UPGRADE_FACTOR 1.15
#define HANDLING_UPGRADE_FACTOR 1.3
#define NITRO_UPGRADE_FACTOR 1.1
#define LIFE_UPGRADE_FACTOR 1.5
#define BRAKE_UPGRADE_FACTOR 1.15
#define MASS_UPGRADE_FACTOR 0.9
#define RACE_START_TIME 3000
#define MAX_RACES 5

//MENU INITIAL COMMANDS
#define SEND_DISCONNECT 0x00
#define SEND_CONNECT 0x01
#define SEND_SELECT_CAR 0x02
#define SEND_READY_TO_PLAY 0x03
#define SEND_QUIT 0x04
#define SEND_CREATE_GAME 0x05
#define SEND_JOIN_GAME 0x06
#define SEND_AVAILABLE_GAMES 0x07
#define RECIVE_AVAILABLE_GAMES 0x08


//CAR CONTROLS COMMANDS
#define SEND_ACCELERATE 0x10
#define SEND_ROTATE_RIGHT 0x11
#define SEND_ROTATE_LEFT 0x12
#define SEND_BRAKE 0x13
#define SEND_USE_NITRO 0x14

//UPGRADES COMMANDS
#define SEND_LIFE_UPGRADE 0x20
#define SEND_BRAKE_UPGRADE 0x21
#define SEND_ACCELERATION_UPGRADE 0x22
#define SEND_HANDLING_UPGRADE 0x23
#define SEND_MASS_UPGRADE 0x24
#define SEND_NITRO_UPGRADE 0x25

// DOWNGRADES COMMAND
#define SEND_LIFE_DOWNGRADE 0x26
#define SEND_BRAKE_DOWNGRADE 0x27
#define SEND_ACCELERATION_DOWNGRADE 0x28
#define SEND_HANDLING_DOWNGRADE 0x29
#define SEND_MASS_DOWNGRADE 0x2A
#define SEND_NITRO_DOWNGRADE 0x2B

//CHEATS COMMANDS
#define SEND_WIN_RACE_CHEAT 0x30
#define SEND_RESTORE_LIFE_CHEAT 0x31
#define SEND_INFINITE_LIFE_CHEAT 0x32
#define SEND_LOSE_RACE_CHEAT 0x33
#define SEND_INFINITE_NITRO_CHEAT 0x34

// STATUS CONSTS
#define SEND_OK_MESSAGE 0x98
#define SEND_ERROR_MESSAGE 0x99


#endif  // CONSTANTS_H
