#ifndef TALLER_TP_UPGRADES_H
#define TALLER_TP_UPGRADES_H

enum Upgrades {
    NONE_UPGRADE,
    ACCELERATION_UPGRADE,
    HANDLING_UPGRADE,
    NITRO_UPGRADE,
    LIFE_UPGRADE,
    BRAKE_UPGRADE,
    MASS_UPGRADE
};

#endif  // TALLER_TP_UPGRADES_H
